Arizona Cardinals: "ARI"
Atlanta Falcons: "ATL"
Baltimore Ravens: "BAL"
Buffalo Bills: "BUF"
Carolina Panthers: "CAR"
Chicago Bears: "CHI"
Cincinatti Bengals: "CIN"
Cleveland Browns: "CLE"
Dallas Cowboys: "DAL"
Denver Broncos: "DEN"
Detroit Lions: "DET"
Green Bay Packers: "GB"
Houston Texans: "HOU"
Indianapolis Colts: "IND"
Jacksonville Jaguars: "JAG"
Kansas City Chiefs: "KAN"
Miami Dolphins: "MIA"
Minnesota Vikings: "MIN"
New England Patriots: "NE"
New Orleans Saints: "NO"
New York Giants: "NYG"
New York Jets: "NYJ"
Oakland Raiders: "OAK"
Philadelphia Eagles: "PHI"
Pittsburgh Steelers: "PIT"
San Diego Chargers: "SD"
San Francisco 49ers: "SF"
Seattle Sehawks: "SEA"
St. Louis Rams: "SL"
Tampa Bay Bucanneers: "TB"
Tenessee Titans: "TEN"
Washington Redskins: "WAS"
